language: c
dist: bionic

before_install:
  - sudo service postgresql stop
  - sudo apt-get remove postgresql* -y
  - sudo apt-get install -q postgresql-server-dev-12 postgresql-client-12 postgresql-12-postgis-3 libcunit1-dev valgrind
  - sudo pg_dropcluster --stop 12 main
  - sudo rm -rf /etc/postgresql/12 /var/lib/postgresql/12
  - sudo pg_createcluster -u postgres 12 main -- --auth-local trust --auth-host password
  - sudo /etc/init.d/postgresql start 12 || sudo journalctl -xe
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres

install:
  - sudo apt-get install -qq g++
  - export CXX="g++"
  - sh .install-lazperf.sh
  - nvm install 8
  - npm install -g eclint@1.1.5

script:
  - eclint check * */* */cunit/*
  - ./tools/build-install.sh # test compilation without lazperf
  - ./tools/build-install.sh --with-lazperf=/usr/local && make check && ./tools/valgrind.sh
  - make installcheck || { cat pgsql/regression.diffs && false; }
  - (cd tools/benchmark_compression && sh compression_benchmark.sh)
